# Site settings
title: Grayscale
email: ste.rebu@outlook.it
url: https://srebughini.github.io/BEERQ/
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ASALIcode
  - title: facebook
    url: https://www.facebook.com/ASALIcode/
  - title: linkedin
    url: https://www.linkedin.com/company/asalicode
  - title: github
    url: https://github.com/srebughini/BEERQ
  - title: reddit
    url: https://www.reddit.com/user/ASALIcode/

# Build settings
markdown: kramdown
permalink: pretty
